language: node_js

node_js:
  - node # latest node
  #- 7.4.0 # vscode latest insiders
  #- 6 # vscode > 1.8.1
  #- 6.5.0 # vscode 1.8.1

cache: yarn

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install: 
  - npm install
  - npm run vscode:prepublish

script:
  - npm test --silent

after_success:
  - bash <(curl -s https://codecov.io/bash)  